[2022-02-10 12:31:57,681] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: spark_first_run.spark_job 2022-02-10T12:31:50.245165+00:00 [queued]>
[2022-02-10 12:31:57,879] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: spark_first_run.spark_job 2022-02-10T12:31:50.245165+00:00 [queued]>
[2022-02-10 12:31:57,879] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 12:31:57,880] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-02-10 12:31:57,880] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 12:31:57,927] {taskinstance.py:1107} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2022-02-10T12:31:50.245165+00:00
[2022-02-10 12:31:57,934] {standard_task_runner.py:52} INFO - Started process 46 to run task
[2022-02-10 12:31:57,941] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spark_first_run', 'spark_job', '2022-02-10T12:31:50.245165+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpz3qgb4i3', '--error-file', '/tmp/tmpof6bifgl']
[2022-02-10 12:31:57,942] {standard_task_runner.py:77} INFO - Job 3: Subtask spark_job
[2022-02-10 12:31:58,288] {logging_mixin.py:104} INFO - Running <TaskInstance: spark_first_run.spark_job 2022-02-10T12:31:50.245165+00:00 [running]> on host af54f92459ec
[2022-02-10 12:31:58,527] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=spark_first_run
AIRFLOW_CTX_TASK_ID=spark_job
AIRFLOW_CTX_EXECUTION_DATE=2022-02-10T12:31:50.245165+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-10T12:31:50.245165+00:00
[2022-02-10 12:31:58,547] {spark_submit.py:228} INFO - Could not load connection string spark_default, defaulting to yarn
[2022-02-10 12:31:58,551] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=spark://spark:7077 --name test --verbose /opt/bitnami/spark/app/test.py
[2022-02-10 12:32:19,778] {spark_submit.py:514} INFO - Using properties file: null
[2022-02-10 12:32:20,412] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2022-02-10 12:32:20,412] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.8/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2022-02-10 12:32:20,412] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2022-02-10 12:32:20,413] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2022-02-10 12:32:20,413] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2022-02-10 12:32:20,605] {spark_submit.py:514} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2022-02-10 12:32:20,606] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2022-02-10 12:32:20,606] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2022-02-10 12:32:20,606] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2022-02-10 12:32:20,606] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2022-02-10 12:32:20,606] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1026)
[2022-02-10 12:32:20,606] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1026)
[2022-02-10 12:32:20,606] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2022-02-10 12:32:20,606] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
[2022-02-10 12:32:20,607] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
[2022-02-10 12:32:20,607] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2022-02-10 12:32:20,668] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 182, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 445, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark:7077 --name test --verbose /opt/bitnami/spark/app/test.py. Error code is: 1.
[2022-02-10 12:32:20,722] {taskinstance.py:1544} INFO - Marking task as FAILED. dag_id=spark_first_run, task_id=spark_job, execution_date=20220210T123150, start_date=20220210T123157, end_date=20220210T123220
[2022-02-10 12:32:20,797] {local_task_job.py:151} INFO - Task exited with return code 1
